"""Add github model

Revision ID: 22d18de9decd
Revises: 2d33b5d9977a
Create Date: 2016-01-25 17:05:44.456193

"""

# revision identifiers, used by Alembic.
revision = '22d18de9decd'
down_revision = '2d33b5d9977a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github', sa.Column('contributors', sa.Integer(), nullable=True))
    op.add_column('github', sa.Column('development_activity', sa.String(length=20), nullable=True))
    op.add_column('github', sa.Column('first_commit', sa.DateTime(), nullable=True))
    op.add_column('github', sa.Column('forks', sa.Integer(), nullable=True))
    op.add_column('github', sa.Column('issues', sa.Integer(), nullable=True))
    op.add_column('github', sa.Column('last_commit', sa.DateTime(), nullable=True))
    op.add_column('github', sa.Column('pull_requests', sa.Integer(), nullable=True))
    op.add_column('github', sa.Column('watchers', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github', 'watchers')
    op.drop_column('github', 'pull_requests')
    op.drop_column('github', 'last_commit')
    op.drop_column('github', 'issues')
    op.drop_column('github', 'forks')
    op.drop_column('github', 'first_commit')
    op.drop_column('github', 'development_activity')
    op.drop_column('github', 'contributors')
    ### end Alembic commands ###
